


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."category" (
    "category_id" bigint NOT NULL,
    "user_id" "uuid",
    "name" "text" NOT NULL,
    "icon_url" "text",
    "sort" integer,
    "created_time" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."category" OWNER TO "postgres";


ALTER TABLE "public"."category" ALTER COLUMN "category_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."category_category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."favorites" (
    "user_id" "uuid" NOT NULL,
    "media_id" bigint NOT NULL,
    "created_time" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."favorites" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."location" (
    "location_id" bigint NOT NULL,
    "user_id" "uuid",
    "cluster_id" bigint,
    "lat" double precision DEFAULT 0 NOT NULL,
    "lon" double precision DEFAULT 0 NOT NULL,
    "country_code" "text",
    "address_text" "text",
    "created_time" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."location" OWNER TO "postgres";


ALTER TABLE "public"."location" ALTER COLUMN "location_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."location_location_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."media" (
    "media_id" bigint NOT NULL,
    "user_id" "uuid",
    "category_id" bigint,
    "location_id" bigint,
    "media_type" "text" DEFAULT 'IMAGE'::"text",
    "file_url" "text" NOT NULL,
    "thumbnail_url" "text",
    "file_size" bigint,
    "take_time" timestamp with time zone,
    "created_time" timestamp with time zone DEFAULT "now"(),
    "edited_time" timestamp with time zone
);


ALTER TABLE "public"."media" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."media_description" (
    "media_id" bigint NOT NULL,
    "description_text" "text",
    "edited_time" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."media_description" OWNER TO "postgres";


ALTER TABLE "public"."media" ALTER COLUMN "media_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_media_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."category"
    ADD CONSTRAINT "category_pkey" PRIMARY KEY ("category_id");



ALTER TABLE ONLY "public"."favorites"
    ADD CONSTRAINT "favorites_pkey" PRIMARY KEY ("user_id", "media_id");



ALTER TABLE ONLY "public"."location"
    ADD CONSTRAINT "location_pkey" PRIMARY KEY ("location_id");



ALTER TABLE ONLY "public"."media_description"
    ADD CONSTRAINT "media_description_pkey" PRIMARY KEY ("media_id");



ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "media_pkey" PRIMARY KEY ("media_id");



CREATE INDEX "idx_category_user_id" ON "public"."category" USING "btree" ("user_id");



CREATE INDEX "idx_favorites_media_id" ON "public"."favorites" USING "btree" ("media_id");



CREATE INDEX "idx_favorites_user_id" ON "public"."favorites" USING "btree" ("user_id");



CREATE INDEX "idx_location_user_id" ON "public"."location" USING "btree" ("user_id");



CREATE INDEX "idx_media_category_id" ON "public"."media" USING "btree" ("category_id");



CREATE INDEX "idx_media_location_id" ON "public"."media" USING "btree" ("location_id");



CREATE INDEX "idx_media_user_id_created_time" ON "public"."media" USING "btree" ("user_id", "created_time" DESC);



ALTER TABLE ONLY "public"."category"
    ADD CONSTRAINT "category_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."favorites"
    ADD CONSTRAINT "favorites_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "public"."media"("media_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."favorites"
    ADD CONSTRAINT "favorites_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."location"
    ADD CONSTRAINT "location_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "media_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."category"("category_id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."media_description"
    ADD CONSTRAINT "media_description_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "public"."media"("media_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "media_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."location"("location_id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "media_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE "public"."category" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "category delete own" ON "public"."category" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "category insert own" ON "public"."category" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "category select own" ON "public"."category" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "category update own" ON "public"."category" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."favorites" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "favorites delete own" ON "public"."favorites" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "favorites insert own" ON "public"."favorites" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "favorites select own" ON "public"."favorites" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."location" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "location delete own" ON "public"."location" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "location insert own" ON "public"."location" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "location select own" ON "public"."location" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "location update own" ON "public"."location" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."media" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "media delete own" ON "public"."media" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "media insert own" ON "public"."media" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "media select own" ON "public"."media" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "media update own" ON "public"."media" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."media_description" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "media_description delete own" ON "public"."media_description" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."media"
  WHERE (("media"."media_id" = "media_description"."media_id") AND ("media"."user_id" = "auth"."uid"())))));



CREATE POLICY "media_description insert own" ON "public"."media_description" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."media"
  WHERE (("media"."media_id" = "media_description"."media_id") AND ("media"."user_id" = "auth"."uid"())))));



CREATE POLICY "media_description select own" ON "public"."media_description" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."media"
  WHERE (("media"."media_id" = "media_description"."media_id") AND ("media"."user_id" = "auth"."uid"())))));



CREATE POLICY "media_description update own" ON "public"."media_description" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."media"
  WHERE (("media"."media_id" = "media_description"."media_id") AND ("media"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."media"
  WHERE (("media"."media_id" = "media_description"."media_id") AND ("media"."user_id" = "auth"."uid"())))));










CREATE POLICY "users can insert own categories" ON "public"."category" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users can insert own descriptions" ON "public"."media_description" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."media"
  WHERE (("media"."media_id" = "media_description"."media_id") AND ("media"."user_id" = "auth"."uid"())))));



CREATE POLICY "users can insert own locations" ON "public"."location" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users can insert own media" ON "public"."media" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."category" TO "anon";
GRANT ALL ON TABLE "public"."category" TO "authenticated";
GRANT ALL ON TABLE "public"."category" TO "service_role";



GRANT ALL ON SEQUENCE "public"."category_category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."category_category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."category_category_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."favorites" TO "anon";
GRANT ALL ON TABLE "public"."favorites" TO "authenticated";
GRANT ALL ON TABLE "public"."favorites" TO "service_role";



GRANT ALL ON TABLE "public"."location" TO "anon";
GRANT ALL ON TABLE "public"."location" TO "authenticated";
GRANT ALL ON TABLE "public"."location" TO "service_role";



GRANT ALL ON SEQUENCE "public"."location_location_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."location_location_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."location_location_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."media" TO "anon";
GRANT ALL ON TABLE "public"."media" TO "authenticated";
GRANT ALL ON TABLE "public"."media" TO "service_role";



GRANT ALL ON TABLE "public"."media_description" TO "anon";
GRANT ALL ON TABLE "public"."media_description" TO "authenticated";
GRANT ALL ON TABLE "public"."media_description" TO "service_role";



GRANT ALL ON SEQUENCE "public"."media_media_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_media_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_media_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







